apiVersion: v1
kind: Namespace
metadata:
  name: dev

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeos
  namespace: default
---

apiVersion: v1
kind: Secret
metadata:
  name: kubeos
  namespace: default
  annotations:
    kubernetes.io/service-account.name: kubeos
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeos-read-only
rules:
  - apiGroups:
      - '*'
    resources:
      - pods
      - pods/log
      - pods/exec
      - configmaps
      - services
      - deployments
      - replicasets
      - horizontalpodautoscalers
      - ingresses
      - statefulsets
      - limitranges
      - daemonsets
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeos-cluster-view-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeos-read-only
subjects:
  - kind: ServiceAccount
    name: kubeos 
    namespace: default
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exec-pods-dev-account
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: terminal-account
roleRef:
  kind: Role
  name: pod-exec-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-exec-role
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]