apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: dev-experience
  description: Everything related to Dev Experience
  title: Internal Developer Platform
  links:
    - url: http://example.com/domain/artists/
      title: Domain Readme
    - url: http://example.com/domains/artists/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: platform-engineering-team
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: core-services
  description: Everything related to core-services
  title: Core Services
  links:
    - url: http://example.com/domain/artists/
      title: Domain Readme
    - url: http://example.com/domains/artists/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: product