apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: internal-developer-platform
  description: Everything related to kubeos
  title: Internal Developer Platform
  links:
    - url: http://example.com/domain/artists/
      title: Domain Readme
    - url: http://example.com/domains/artists/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: platform-engineering-team